[package]
name = "replicant_toolkit"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
eframe = "0.31.1"
egui-notify = "0.19.0"
egui-phosphor = "0.9.0"
egui_extras = "0.31.1"
rfd = "0.15.3"
zstd = "0.13.3"
