name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    name: Build windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: Cyberboss/install-winget@v1
      - name: Install dependencies
        run: |
          winget install jqlang.jq
        shell: pwsh

      - name: Get binary name
        run: |
          $BINARY_NAME = cargo read-manifest | jq -r '.name'
          Write-Host "Detected binary name: $BINARY_NAME"
          echo "BINARY=$BINARY_NAME" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
      - name: Compile ${{ matrix.target }}
        id: compile
        run: cargo build --profile release
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY }}_${{ matrix.target }}_${{ matrix.profile }}
          path: |
            target/${{ matrix.profile }}/${{ env.BINARY }}
            target/${{ matrix.profile }}/${{ env.BINARY }}.*
