name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        profile: [release]
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq mingw-w64 musl-tools
      
      - name: Install target ${{ matrix.target }}
        run: rustup target add ${{ matrix.target }}

      - name: Get binary name
        run: |
          BINARY_NAME=$(cargo metadata --format-version 1 | jq -r '.packages[0].name')
          echo "BINARY=${BINARY_NAME}" >> $GITHUB_ENV

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
      - name: Compile ${{ matrix.target }}
        id: compile
        run: cargo build --profile ${{ matrix.profile }} --target ${{ matrix.target }}
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY }}_${{ matrix.target }}_${{ matrix.profile }}
          path: |
            target/${{ matrix.profile }}/${{ env.BINARY }}
            target/${{ matrix.profile }}/${{ env.BINARY }}.*
