name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        profile: [release]
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-docker-action@v4
      
      - name: Install dependencies
        run: |
          cargo install cross --git https://github.com/cross-rs/cross

      - name: Get binary name
        run: |
          BINARY_NAME=$(cargo read-manifest | jq -r '.name')
          echo "Detected binary name: $BINARY_NAME"
          echo "BINARY=${BINARY_NAME}" >> $GITHUB_ENV

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
      - name: Compile ${{ matrix.target }}
        id: compile
        run: cross build --profile ${{ matrix.profile }} --target ${{ matrix.target }}
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY }}_${{ matrix.target }}_${{ matrix.profile }}
          path: |
            target/${{ matrix.target }}/${{ matrix.profile }}/${{ env.BINARY }}
            target/${{ matrix.target }}/${{ matrix.profile }}/${{ env.BINARY }}.*
