name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    name: Build windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
      - name: Compile ${{ matrix.target }}
        id: compile
        run: cargo build --profile release
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: replicant_toolkit-release
          path: |
            target/release/replicant_toolkit
            target/release/replicant_toolkit.*
